(function(){
  const nav='<div class="demo-nav"><i>⌂<small>Home</small></i><i>☆<small>Learning</small></i><i>▣<small>Course</small></i><i>◫<small>KSB’s</small></i><i>▤<small>Documents</small></i><i>⚙<small>Settings</small></i></div>';
  const screen=(type,focus='')=>{
    const H=x=>`<div class="${focus===x?'demo-focus':''}">`;
    const end='</div>';
    const screens={
      welcome:`<div class="demo-welcome"><img src="logo.png"><b>Apprentice+</b><span>Your Course, Your Way</span></div>`,
      navigation:`<div class="demo-mini-header">Apprentice+</div><div class="demo-placeholder tall">Your current page</div>${nav}`,
      home:`<div class="demo-mini-header">Home</div>${H('progress')}<div class="demo-tile"><small>COURSE PROGRESS</small><b>27%</b><div class="demo-bar"><i></i></div></div>${end}${H('next')}<div class="demo-next"><small>WHAT SHOULD I DO NEXT?</small><b>Complete Assignment 4</b><button>Open assignment</button></div>${end}<div class="demo-row"><div>XP & badges</div><div>Rewards</div></div>${nav}`,
      learning:`<div class="demo-mini-header">Learning</div>${['Revision Packs','Functional Skills','CSCS','In-house Training','Learner Notepad'].map((x,i)=>`${H(`learn${i}`)}<div class="demo-list-row"><span>${['📚','∑','⛑','★','✎'][i]}</span><b>${x}</b><i>›</i></div>${end}`).join('')}${nav}`,
      course:`<div class="demo-mini-header">Course</div><div class="demo-course-tabs">${H('as')}<button class="as">Assignments<b>AS</b></button>${end}<div class="support"><small>SUPPORTING EVIDENCE</small>${['TA','PA','WT','EPA'].map(x=>`${H(x.toLowerCase())}<button>${x}</button>${end}`).join('')}</div></div><div class="demo-workflow">Assignment › TA, PA or WT › Upload ✓</div>${nav}`,
      list:`<div class="demo-mini-header">Assignments</div>${[1,2,3].map((n,i)=>`${H(i===0?'item':'')}<div class="demo-list-row"><span>${n}</span><b>Assignment ${n}: ${['Health & Safety','Safe Systems of Work','Environmental Practice'][i]}</b><i>›</i></div>${end}`).join('')}${nav}`,
      assignment:`<div class="demo-mini-header">Assignment 1</div><div class="demo-tile"><b>Health & Safety</b><small>K1 · K3 · S1 · B1</small></div>${H('photos')}<div class="demo-photo-grid">${[1,2,3,4,5,6].map(n=>`<i>＋<small>Photo ${n}</small></i>`).join('')}</div>${end}${H('prompts')}<div class="demo-prompts"><i>● Safe workspace</i><i>● PPE</i><i>● Risk assessment</i></div>${end}${H('text')}<div class="demo-textarea">Type your activity statement here…</div>${end}${H('complete')}<button class="demo-complete">Complete assignment</button>${end}${nav}`,
      chooser:`<div class="demo-mini-header">Add photo</div><div class="demo-sheet"><b>What this photo should show</b><p>Clear evidence of you completing the required skill.</p>${H('camera')}<button>📷 Take a photo</button>${end}${H('gallery')}<button>🖼 Choose from gallery</button>${end}</div>${nav}`,
      ta:`<div class="demo-mini-header">Trade Academy</div><div class="demo-question"><small>QUESTION 1 OF 10</small><b>Which control should be checked first?</b>${['Answer A','Answer B','Answer C','Answer D'].map(x=>`<button>${x}</button>`).join('')}${H('confirm')}<button class="confirm">Confirm & next</button>${end}</div>${nav}`,
      pa:`<div class="demo-mini-header">Practical Assessment</div><div class="demo-tile"><b>Practical task</b><p>Assessor observes and scores each area.</p></div>${H('marks')}<div class="demo-score-grid">${['Setting out','Accuracy','Quality','Safe working'].map(x=>`<label>${x}<span>1 2 3 4 5</span></label>`).join('')}</div>${end}${H('signature')}<div class="demo-sign">Assessor signature</div>${end}${nav}`,
      wt:`<div class="demo-mini-header">Witness Testimony</div>${H('details')}<div class="demo-input">Witness name and job title</div>${end}${H('statement')}<div class="demo-textarea">Describe exactly what was observed…</div>${end}${H('signature')}<div class="demo-sign">Witness signature</div>${end}${nav}`,
      documents:`<div class="demo-mini-header">Documents</div>${H('ready')}<div class="demo-zone"><small>READY TO UPLOAD</small><b>Download completed assignment</b><button>Download evidence</button></div>${end}${H('library')}<div class="demo-zone library"><small>DOCUMENT LIBRARY</small><div>AS　TA　PA</div><div>WT　EPA　AC</div></div>${end}${nav}`,
      ksb:`<div class="demo-mini-header">KSB’s</div>${H('gap')}<button class="demo-gap">Show incomplete KSB’s only</button>${end}${['K1 Health & Safety','S1 Safe working','B1 Professional conduct'].map(x=>`<div class="demo-list-row"><b>${x}</b><span>AS · TA/PA · WT</span></div>`).join('')}${nav}`,
      settings:`<div class="demo-mini-header">Settings</div>${['Learner Profile','Reading & Notifications','App & Updates','Developer Mode'].map((x,i)=>`${H(`setting${i}`)}<div class="demo-list-row"><b>${x}</b><i>＋</i></div>${end}`).join('')}${nav}`,
      recap:`<div class="demo-recap"><b>Your evidence journey</b><span>1　Complete Assignment (AS)</span><i>↓</i><span>2　Add TA, PA or WT</span><i>↓</i><span>3　Download evidence</span><i>↓</i><span>4　Upload to your portfolio</span><i>↓</i><span>5　Tap Uploaded ✓</span></div>`,
      disclaimer:`<div class="demo-disclaimer"><b>Protect and submit your work</b><p>Apprentice+ stores its data and evidence locally on this device. Work completed inside the app is not automatically submitted to your college, provider, employer or online portfolio.</p><p>You must download completed evidence and upload it to the online portfolio specified by your provider. Keep backups and do not clear the app’s data before your evidence is safely uploaded.</p><label><input id="demoDisclaimerCheck" type="checkbox"> I understand that my evidence is stored locally and must be uploaded.</label></div>`
    };return `<div class="demo-phone">${screens[type]||screens.home}</div>`;
  };
  const full=[
    ['welcome','','Welcome to Apprentice+','This demonstration shows you how to complete assignments, add supporting evidence and prepare files for your online portfolio.'],
    ['navigation','','The bottom navigation','These six buttons take you to every main area of Apprentice+. We will look at each one first.'],
    ['home','progress','Home','Home shows assignment progress, the next recommended action, XP, badges, rewards and unlocked Mate tools.'],
    ['learning','','Learning','Learning contains revision packs, Functional Skills, CSCS preparation, in-house training and the Learner Notepad.'],
    ['course','','Course','Course contains primary Assignments, supporting TA, PA and WT evidence, plus EPA practice.'],
    ['ksb','gap','KSB’s','The matrix shows completed Knowledge, Skills and Behaviours. The gap finder concentrates on what remains.'],
    ['documents','library','Documents','Ready to Upload prepares evidence bundles. Document Library stores individual PDFs.'],
    ['settings','','Settings','Add your profile, signature and portfolio link, then manage accessibility, notifications and updates.'],
    ['home','next','What Should I Do Next?','This card always leads you to the next assignment action. Tap its button to open the correct place.'],
    ['course','as','Assignments are primary evidence','Tap the large green AS box. An Assignment is always the main evidence for each part of your course.'],
    ['list','item','Choose an assignment','Tap an assignment to begin. Its status changes as you progress through evidence and upload.'],
    ['assignment','','Read the assignment','Check the title, instructions and KSB tags before collecting evidence.'],
    ['assignment','photos','Add six photographs','Tap each photo space. Your photographs should clearly show you personally completing the required work.'],
    ['chooser','gallery','Camera or gallery','Take a new photograph or choose an existing image from your phone gallery.'],
    ['assignment','text','Write your statement','Explain what you did, tools and materials, safe working, checks and problems you solved.'],
    ['assignment','prompts','Turn the prompts green','The required KSB prompts turn green when your statement contains suitable information.'],
    ['assignment','complete','Complete the quality check','Six photos, 100 words, every prompt and your saved signature must be ready before completion.'],
    ['course','ta','Choose one supporting item','After AS, add any one supporting item: TA, PA or WT. You do not need all three.'],
    ['ta','confirm','Trade Academy (TA)','Choose an answer and press Confirm. TA provides Knowledge and Behaviour supporting evidence.'],
    ['pa','marks','Practical Assessment (PA)','An assessor observes the task, scores each area, adds feedback and signs the mark sheet.'],
    ['wt','statement','Witness Testimony (WT)','A suitable workplace witness records what they observed, adds their details and signs it.'],
    ['documents','ready','Download and upload','Download the completed assignment bundle, upload it to your portfolio, then tap Uploaded ✓ in Apprentice+.'],
    ['recap','','Assignment workflow recap','Complete AS, add one of TA, PA or WT, download the files, upload them and confirm Uploaded ✓.'],
    ['disclaimer','','Important information','Your app data remains on this device until you download and upload it. Please confirm that you understand.']
  ];
  const tours={
    home:[['home','progress','Course progress','This percentage is based on completed Assignments. Expand the section for supporting evidence detail.'],['home','next','Your next action','Follow this card to continue the correct assignment workflow.'],['home','','Achievements and tools','Expand the remaining sections to see XP, badges, rewards and Mate apps.']],
    academy:[['learning','learn0','Revision packs','Use guided packs to learn before taking assessments.'],['learning','learn1','Functional Skills','Complete the Maths and English practice at the stated level.'],['learning','learn4','Learner Notepad','Save personal notes, dictated text and reference images here.']],
    apprenticeship:[['course','as','Assignments','AS is your primary evidence and the most important place to begin.'],['course','ta','Supporting evidence','Add one TA, PA or WT item after completing the matching Assignment.'],['course','epa','EPA practice','Use the three challenging mocks when preparing for End Point Assessment.']],
    assignment:[['assignment','photos','Photographic evidence','Tap all six spaces to use the camera or gallery.'],['assignment','prompts','KSB prompts','Cover each prompt in your own activity statement until it turns green.'],['assignment','text','Activity statement','Write at least 100 words explaining the full activity.'],['assignment','complete','Complete','Submit only when every quality check has passed.']],
    ta:[['ta','','Question slide','Read the question and every possible answer carefully.'],['ta','confirm','Confirm your answer','Choose an answer, then confirm to move to the next slide.']],
    pa:[['pa','marks','Assessment scores','The assessor scores every generic and skill-specific area.'],['pa','signature','Assessor signature','Feedback, assessor details and a signature are required before saving.']],
    wt:[['wt','details','Witness details','The witness records their identity and workplace role.'],['wt','statement','Observed evidence','They describe what they personally saw the apprentice do.'],['wt','signature','Witness signature','The completed testimony must be signed before saving.']],
    ksb:[['ksb','gap','KSB gap finder','Show only incomplete KSBs when planning the next evidence.'],['ksb','','Evidence markers','Tap an AS, TA, PA or WT marker to open that evidence item.']],
    documents:[['documents','ready','Ready to Upload','Download one completed assignment or the full portfolio.'],['documents','library','Document Library','Open a category, select a PDF and download it.']],
    settings:[['settings','setting0','Learner Profile','Save your name, signature and online portfolio link.'],['settings','setting1','Reading and notifications','Choose accessibility support and the messages you receive.'],['settings','setting2','App and updates','Install Apprentice+ and check approved releases.']],
    notepad:[['learning','learn4','Create and save notes','Add a title, text or dictation and up to six images.'],['chooser','gallery','Add images','Choose several gallery images or take a new photograph.']],
    epa:[['course','epa','EPA practice','Open the knowledge mock, practical mock or professional discussion.'],['ta','confirm','Slide controls','Work through each mock one slide at a time and save the final record.']],
    rewards:[['home','','Rewards and Mate apps','Claim earned rewards and open tools unlocked by assignment progress.']]
  };
  const briefs={
    home:'Your progress dashboard. It shows completed Assignments, the next required action, XP, badges, rewards and unlocked Mate tools.',
    academy:'Learning contains revision, Functional Skills, CSCS preparation, in-house training and the Learner Notepad.',
    apprenticeship:'Complete an Assignment as primary evidence, add one TA, PA or WT supporting item, then download and upload the evidence.',
    assignment:'Add six relevant photographs and a 100-word activity statement that covers every KSB prompt before completing the Assignment.',
    ta:'Answer the assignment-specific questions to create Knowledge and Behaviour supporting evidence.',
    pa:'An assessor scores and signs a practical task linked to the course Skills.',
    wt:'A workplace witness records and signs what they personally observed the apprentice completing.',
    ksb:'The matrix shows every Knowledge, Skill and Behaviour, its evidence and any remaining gaps.',
    documents:'Prepare evidence for portfolio upload or open individual PDFs from the Document Library.',
    settings:'Manage the learner profile, accessibility, notifications, installation, updates and protected developer controls.',
    notepad:'Create private notes containing text, dictation and reference images stored on this device.',
    epa:'Practise the course-specific EPA knowledge test, practical assessment and professional discussion.',
    rewards:'View unlocked Apprentice+ tools, colour themes and agreed reward cards.'
  };
  function contextKey(){
    if(view.assignment)return'assignment';if(view.academyModule)return'ta';if(view.practicalAssessment)return'pa';if(view.witnessAssignment)return'wt';if(view.epaMock)return'epa';if(view.notepad)return'notepad';if(view.tab==='academy')return'academy';if(view.tab==='apprenticeship')return'apprenticeship';return tours[view.tab]?view.tab:'home';
  }
  function run(slides,isFull=false){
    let index=0;const wrap=document.createElement('div');wrap.className='guided-demo-overlay';document.body.appendChild(wrap);
    const paint=()=>{const [type,focus,title,text]=slides[index],last=index===slides.length-1;wrap.innerHTML=`<div class="guided-demo-shell"><div class="demo-top"><b>${isFull?'APPRENTICE+ GUIDED DEMO':'PAGE DEMO'}</b><button id="exitGuidedDemo">×</button></div><div class="demo-progress"><i style="width:${(index+1)/slides.length*100}%"></i></div><div class="demo-stage">${screen(type,focus)}<div class="demo-speech"><small>${index+1} OF ${slides.length}</small><h2>${title}</h2><p>${text}</p></div></div><div class="demo-controls"><button id="demoBack" ${index===0?'disabled':''}>‹ Back</button><button id="demoNext" ${last&&type==='disclaimer'?'disabled':''}>${last?'Finish':'Next ›'}</button></div></div>`;$('#exitGuidedDemo',wrap).onclick=()=>wrap.remove();$('#demoBack',wrap).onclick=()=>{index--;paint()};const next=$('#demoNext',wrap);if(type==='disclaimer'){$('#demoDisclaimerCheck',wrap).onchange=e=>next.disabled=!e.target.checked}next.onclick=()=>{if(last){if(isFull){state.demoCompleted=true;state.demoDisclaimerAccepted=true;save()}wrap.remove();if(isFull)toast('Demo completed')}else{index++;paint()}}};
    paint();
  }
  window.openFullAppDemo=()=>run(full,true);
  window.openPageDemo=()=>run(tours[contextKey()]||tours.home,false);
  window.showPageInformation=function(title){
    const key=contextKey(),wrap=document.createElement('div');wrap.className='modal-wrap app-notification-wrap';wrap.innerHTML=`<div class="modal-card page-information-modal brief-page-info"><div class="page-information-icon">i</div><small>WHAT’S THIS PAGE ABOUT?</small><h3>${esc(title)}</h3><p>${esc(briefs[key]||'This page helps you record, understand or manage your apprenticeship progress.')}</p><div class="brief-info-actions"><button class="btn btn-secondary" id="closeBriefInfo">OK, got it</button><button class="btn btn-primary" id="startPageDemo">Show me around</button></div></div>`;document.body.appendChild(wrap);$('#closeBriefInfo',wrap).onclick=()=>wrap.remove();$('#startPageDemo',wrap).onclick=()=>{wrap.remove();openPageDemo()};
  };
  const modal=(title,body)=>{const wrap=document.createElement('div');wrap.className='modal-wrap app-notification-wrap';wrap.innerHTML=`<div class="modal-card support-modal"><button class="document-modal-close" aria-label="Close">×</button><small>APPRENTICE+ SUPPORT</small><h3>${title}</h3>${body}</div>`;document.body.appendChild(wrap);$('.document-modal-close',wrap).onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};return wrap};
  window.showLearnerHelp=()=>modal('Help & frequently asked questions',`<details open><summary>How do I complete an assignment?</summary><p>Add six relevant photographs, write at least 100 words, cover every green prompt and save your signature.</p></details><details><summary>What supporting evidence do I need?</summary><p>Complete one matching TA, PA or WT item after the primary Assignment.</p></details><details><summary>Has my work been submitted automatically?</summary><p>No. Download the completed assignment and upload it to the online portfolio provided by your college or training provider.</p></details><details><summary>Where is my work saved?</summary><p>App data and images are stored locally on this device. Do not clear site data or uninstall before downloading and uploading your evidence.</p></details><details><summary>How do I continue a test?</summary><p>Question activities save their place. Reopen the activity and select Continue or Restart.</p></details><button class="btn btn-primary replay-help-demo">Replay guided demo</button>`);
  window.showPrivacyNotice=()=>modal('Privacy & local data',`<p>Apprentice+ stores learner details, signatures, evidence images, statements, progress, test answers, notes and settings locally on this device.</p><p>The app does not automatically submit evidence to a college, training provider, employer or portfolio. Learners must download and upload their completed evidence themselves.</p><p>Protect access to the device, download regular backups and do not clear browser/app data or uninstall Apprentice+ until all evidence has been safely uploaded.</p><p>Developer Mode contains export and reset controls. Reset permanently removes locally stored app data.</p><button class="btn btn-primary close-privacy">OK, I understand</button>`);
  window.showFeedbackForm=()=>{const wrap=modal('Send feedback',`<label>What happened or what would help?<textarea id="feedbackText" rows="6" placeholder="Describe the page, button or problem…"></textarea></label><label>Feedback type<select id="feedbackType"><option>Problem</option><option>Suggestion</option><option>Question</option></select></label><button class="btn btn-primary" id="shareFeedback">Share feedback report</button><p class="muted">The report includes the app version, selected course and current page, but not your evidence.</p>`);$('#shareFeedback',wrap).onclick=async()=>{const detail=$('#feedbackText',wrap).value.trim();if(!detail)return toast('Describe the feedback first');const report=`Apprentice+ feedback\nType: ${$('#feedbackType',wrap).value}\nVersion: ${APP_VERSION}\nCourse: ${course().name}\nPage: ${view.tab}\n\n${detail}`;if(navigator.share)await navigator.share({title:'Apprentice+ feedback',text:report});else{await navigator.clipboard?.writeText(report);toast('Feedback report copied')}}};
  document.addEventListener('click',e=>{if(e.target.closest('.replay-help-demo')){e.target.closest('.modal-wrap')?.remove();openFullAppDemo()}if(e.target.closest('.close-privacy'))e.target.closest('.modal-wrap')?.remove()});
})();
